name: flutter_keyword_highlighter
description: A Flutter package to highlight specific keywords in text with customizable styles.
version: 0.1.1  # Update the version if needed.
homepage: https://github.com/YoussefMohammed001/flutter_keyword_highlighter  # Replace with your actual URL
repository: https://github.com/YoussefMohammed001/flutter_keyword_highlighter  # Replace with your actual repository URL
issue_tracker: https://github.com/YoussefMohammed001/flutter_keyword_highlighter/issues  # Replace with your actual issue tracker URL

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true