name: flutter_keyword_highlighter
description: "A Flutter package to highlight specific keywords in text."
version: 0.0.3 # Update this to the new version
homepage: https://github.com/YoussefMohammed001/flutter_keyword_highlighter # Replace with your actual URL
repository: https://github.com/YoussefMohammed001/flutter_keyword_highlighter # Add this line
environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true