name: flutter_keyword_highlighter
description: "A Flutter package to highlight specific keywords in text."
version: 0.0.1
homepage: https://github.com/YoussefMohammed001/flutter_keyword_highlighter # Replace with your actual URL

environment:
  sdk: ">=2.17.0 <3.0.0" # Updated Dart SDK version
  flutter: ">=3.0.0"      # Ensure this matches your Flutter version

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

publish_to: 'https://pub.dev'
tag_pattern: 'v{{version}}' # Tag pattern for versioning