name: flutter_keyword_highlighter
description: "A flexible Flutter package for highlighting specific keywords and characters in text with customizable styles, making it perfect for text-based applications and user interfaces."
version: 1.0.7
homepage: https://github.com/YoussefMohammed001/flutter_keyword_highlighter
repository: https://github.com/YoussefMohammed001/flutter_keyword_highlighter
issue_tracker: https://github.com/YoussefMohammed001/flutter_keyword_highlighter/issues


environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.0.0"


dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true