name: flutter_keyword_highlighter
description: "A Flutter package to highlight specific keywords in text."
version: 0.0.2 # Incremented version number
homepage: https://github.com/yourusername/flutter_keyword_highlighter

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true